import {
  Controller,
  Get,
  Post,
  Delete,
  Param,
  Body,
  Query,
  ParseIntPipe,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiParam,
  ApiQuery,
  ApiBody,
} from '@nestjs/swagger';
import { AlertsService } from './alerts.service';
import { CreateAlertDto, ResolveAlertDto, AlertType } from './dto/alert.dto';
import { Alert } from '../entities/alert.entity';

@ApiTags('Alerts')
@Controller('alerts')
export class AlertsController {
  constructor(private readonly alertsService: AlertsService) {}

  @Post()
  @ApiOperation({
    summary: 'Create a new alert',
    description: 'Manually create an alert (typically alerts are auto-generated by the system)',
  })
  @ApiBody({
    type: CreateAlertDto,
    examples: {
      memberLowBalance: {
        summary: 'Member low balance alert',
        value: {
          alert_type: 'member_low_balance',
          member_id: 3,
          message: 'Member balance (200 BDT) below threshold (250 BDT)',
        },
      },
      treasuryLow: {
        summary: 'Treasury low balance alert',
        value: {
          alert_type: 'treasury_low',
          message: 'Treasury balance (4500 BDT) below threshold (5000 BDT)',
        },
      },
    },
  })
  @ApiResponse({
    status: 201,
    description: 'Alert created successfully',
    schema: {
      example: {
        id: 5,
        alert_type: 'member_low_balance',
        member_id: 3,
        message: 'Member balance (200 BDT) below threshold (250 BDT)',
        is_resolved: false,
        resolved_at: null,
        triggered_at: '2025-11-03T10:00:00.000Z',
      },
    },
  })
  @ApiResponse({ status: 400, description: 'Validation failed' })
  create(@Body() createAlertDto: CreateAlertDto): Promise<Alert> {
    return this.alertsService.create(createAlertDto);
  }

  @Get()
  @ApiOperation({
    summary: 'Get all alerts',
    description: 'Retrieve all alerts with optional filtering by resolution status or type',
  })
  @ApiQuery({
    name: 'isResolved',
    required: false,
    type: Boolean,
    description: 'Filter by resolution status (true/false)',
    example: false,
  })
  @ApiQuery({
    name: 'alertType',
    required: false,
    enum: AlertType,
    description: 'Filter by alert type',
    example: 'member_low_balance',
  })
  @ApiResponse({
    status: 200,
    description: 'List of alerts',
    schema: {
      example: [
        {
          id: 5,
          alert_type: 'member_low_balance',
          member_id: 3,
          member: {
            id: 3,
            name: 'Bob Smith',
            balance: '200.00',
          },
          message: 'Member balance (200 BDT) below threshold (250 BDT)',
          is_resolved: false,
          resolved_at: null,
          triggered_at: '2025-11-03T10:00:00.000Z',
        },
      ],
    },
  })
  findAll(
    @Query('isResolved') isResolved?: string,
    @Query('alertType') alertType?: string,
  ): Promise<Alert[]> {
    const options: any = {};
    if (isResolved !== undefined) {
      options.isResolved = isResolved === 'true';
    }
    if (alertType) {
      options.alertType = alertType;
    }
    return this.alertsService.findAll(options);
  }

  @Get('unresolved')
  @ApiOperation({
    summary: 'Get all unresolved alerts',
    description: 'Retrieve only alerts that have not been resolved yet',
  })
  @ApiResponse({
    status: 200,
    description: 'List of unresolved alerts',
    schema: {
      example: [
        {
          id: 5,
          alert_type: 'member_low_balance',
          member_id: 3,
          member: {
            name: 'Bob Smith',
            balance: '200.00',
          },
          message: 'Member balance (200 BDT) below threshold (250 BDT)',
          is_resolved: false,
          triggered_at: '2025-11-03T15:00:00.000Z',
        },
        {
          id: 6,
          alert_type: 'treasury_low',
          message: 'Treasury balance (4500 BDT) below threshold (5000 BDT)',
          is_resolved: false,
          triggered_at: '2025-11-03T16:00:00.000Z',
        },
      ],
    },
  })
  findUnresolved(): Promise<Alert[]> {
    return this.alertsService.findUnresolved();
  }

  @Get('stats')
  @ApiOperation({
    summary: 'Get alert statistics',
    description: 'Retrieve statistics about alerts (total, unresolved, by type)',
  })
  @ApiResponse({
    status: 200,
    description: 'Alert statistics',
    schema: {
      example: {
        total: 12,
        unresolved: 3,
        byType: {
          treasury_low: 2,
          member_low_balance: 5,
          fine_applied: 3,
          consecutive_absence: 2,
        },
      },
    },
  })
  getStats() {
    return this.alertsService.getStats();
  }

  @Get('member/:id')
  @ApiOperation({
    summary: 'Get alerts for a specific member',
    description: 'Retrieve all alerts related to a specific member',
  })
  @ApiParam({
    name: 'id',
    description: 'Member ID',
    example: 3,
  })
  @ApiResponse({
    status: 200,
    description: 'List of member alerts',
    schema: {
      example: [
        {
          id: 5,
          alert_type: 'member_low_balance',
          member_id: 3,
          message: 'Member balance (200 BDT) below threshold (250 BDT)',
          is_resolved: false,
          triggered_at: '2025-11-03T10:00:00.000Z',
        },
        {
          id: 7,
          alert_type: 'consecutive_absence',
          member_id: 3,
          message: 'Member missed 2 consecutive sessions',
          is_resolved: true,
          resolved_at: '2025-11-03T12:00:00.000Z',
          triggered_at: '2025-11-02T18:00:00.000Z',
        },
      ],
    },
  })
  findByMember(@Param('id', ParseIntPipe) id: number): Promise<Alert[]> {
    return this.alertsService.findByMember(id);
  }

  @Get(':id')
  @ApiOperation({
    summary: 'Get a specific alert',
    description: 'Retrieve details of a single alert by ID',
  })
  @ApiParam({
    name: 'id',
    description: 'Alert ID',
    example: 5,
  })
  @ApiResponse({
    status: 200,
    description: 'Alert details',
    schema: {
      example: {
        id: 5,
        alert_type: 'member_low_balance',
        member_id: 3,
        member: {
          id: 3,
          name: 'Bob Smith',
          balance: '200.00',
        },
        message: 'Member balance (200 BDT) below threshold (250 BDT)',
        is_resolved: false,
        resolved_at: null,
        triggered_at: '2025-11-03T10:00:00.000Z',
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  findOne(@Param('id', ParseIntPipe) id: number): Promise<Alert> {
    return this.alertsService.findOne(id);
  }

  @Post(':id/resolve')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Resolve an alert',
    description: 'Mark an alert as resolved with optional notes',
  })
  @ApiParam({
    name: 'id',
    description: 'Alert ID',
    example: 5,
  })
  @ApiBody({
    type: ResolveAlertDto,
    required: false,
    examples: {
      withNotes: {
        summary: 'Resolve with notes',
        value: {
          notes: 'Member added 500 BDT contribution, balance now 700 BDT',
        },
      },
      withoutNotes: {
        summary: 'Resolve without notes',
        value: {},
      },
    },
  })
  @ApiResponse({
    status: 200,
    description: 'Alert resolved successfully',
    schema: {
      example: {
        id: 5,
        alert_type: 'member_low_balance',
        member_id: 3,
        message: 'Member balance (200 BDT) below threshold (250 BDT)\n\nResolution: Member added 500 BDT contribution, balance now 700 BDT',
        is_resolved: true,
        resolved_at: '2025-11-03T12:00:00.000Z',
        triggered_at: '2025-11-03T10:00:00.000Z',
      },
    },
  })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  @ApiResponse({ status: 400, description: 'Alert already resolved' })
  resolve(
    @Param('id', ParseIntPipe) id: number,
    @Body() resolveAlertDto?: ResolveAlertDto,
  ): Promise<Alert> {
    return this.alertsService.resolve(id, resolveAlertDto?.notes);
  }

  @Delete(':id')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    summary: 'Delete an alert',
    description: 'Permanently delete an alert from the system',
  })
  @ApiParam({
    name: 'id',
    description: 'Alert ID',
    example: 5,
  })
  @ApiResponse({ status: 204, description: 'Alert deleted successfully' })
  @ApiResponse({ status: 404, description: 'Alert not found' })
  remove(@Param('id', ParseIntPipe) id: number): Promise<void> {
    return this.alertsService.remove(id);
  }
}
